name: Code Quality Checks

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  pull-requests: read

jobs:
  kotlin-lint:
    name: Kotlin Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Kotlin compiler checks
        run: ./gradlew compileKotlin compileTestKotlin --parallel --build-cache

  dependency-check:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check dependencies
        run: ./gradlew dependencies --configuration runtimeClasspath

  build-verification:
    name: Build Verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Verify build configuration
        run: ./gradlew help --parallel

      - name: Check for circular dependencies
        run: ./gradlew buildEnvironment

  quality-gate:
    name: Quality Gate
    needs: [kotlin-lint, dependency-check, build-verification]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Check all quality checks passed
        run: |
          if [ "${{ needs.kotlin-lint.result }}" != "success" ] || \
             [ "${{ needs.dependency-check.result }}" != "success" ] || \
             [ "${{ needs.build-verification.result }}" != "success" ]; then
            echo "Quality checks failed!"
            exit 1
          fi
          echo "All quality checks passed!"
